services:
    app:
        build: .
        command: npm run dev
        ports:
            - 127.0.0.1:5173:5173
        volumes:
            - ./:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        
volumes:
    node_modules: